#!/bin/sh
# Shared body of the post-checkout and post-merge hooks: warn when the generated
# role CSS no longer matches what the solver produces.
#
# The message deliberately does NOT claim this operation caused it. The hook
# only knows the check failed afterwards, and the drift may equally have been
# sitting in the working tree already; asserting a cause the hook cannot
# observe would send someone hunting for the wrong commit. The heading says
# what was measured — the mismatch — rather than a guess at what produced it.
#
# WHY THIS EXISTS
# The role primitives in src/index.css and src/theme/dark.css, and the alias
# rules in src/index.css, are GENERATED by scripts/role-picker.mjs. They are
# checked into git, which means any command that restores the committed version
# of those files silently reverts the solver's output. That is not cosmetic:
# a reverted token means the app paints a colour the solver never approved, and
# the contrast audits grade a palette that is not the one on screen.
#
# `npm run lint` catches the drift, but lint only runs when someone remembers
# to run it. These hooks run at the instant the revert happens, so the drift is
# reported while the command that caused it is still on screen.
#
# COVERAGE — which git operations call this:
#   git checkout / git switch / git checkout -- <file>  -> post-checkout  FIRES
#   git merge / git pull                                 -> post-merge     FIRES
#   git stash push / git stash pop                       -> NO HOOK FIRES
# Git ships no reference for stash, so a stash cannot be caught here and never
# will be. That gap is why `role:check` also runs inside the `dev` and `build`
# scripts, which cover every way the working tree can come back stale,
# including a stash.
#
# A guard must never block the operation that triggered it. Only speak up.

root=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
cd "$root" || exit 0

output=$(node scripts/role-picker.mjs --check 2>&1)
status=$?

# Exit 2 is "the check could not run here", not "the files have drifted".
# node_modules/tailwindcss/theme.css supplies the palette the solver grades
# against, and a clone that has not run `npm ci` yet has none of it. Printing
# the revert banner there would blame this git operation for a missing install
# — and the advice would be wrong, because there is nothing to restore yet.
if [ $status -eq 2 ]; then
  echo ""
  echo "  (role CSS check skipped — run \`npm ci\` to enable it)"
  echo ""
  exit 0
fi

if [ $status -ne 0 ]; then
  echo ""
  echo "  ┌─────────────────────────────────────────────────────────────┐"
  echo "  │  GENERATED ROLE CSS NO LONGER MATCHES THE SOLVER            │"
  echo "  └─────────────────────────────────────────────────────────────┘"
  echo ""
  echo "$output"
  echo ""
  echo "  The role primitives and alias rules are generated, and no longer"
  echo "  match what the solver produces. This git operation is the most"
  echo "  likely cause — it can restore the committed copy over the solver's"
  echo "  output — but it may also be drift that was already there. Restore"
  echo "  them with:"
  echo ""
  echo "      npm run role:write"
  echo ""
fi

exit 0